In [1]:
import numpy as np

In [163]:
v = np.array([0.,0.,0.,0.,0.,0.])
reward = np.array([0.,0.,0.,0.,1.,0.])

In [88]:
def reward(s):
    if s==4:
        return 1.
    else:
        return 0.

In [113]:
gamma = 0.5
T = 10

In [151]:
for i in range(0,v.shape[0]-1):
    vi = np.copy(v)
    v[i] = reward[i] + gamma*v[i+1]
    print(v-vi)

[0.  0.  0.  0.5 1.  0. ]
[0.  0.  0.  0.5 1.  0. ]
[0.   0.   0.25 0.5  1.   0.  ]
[0.   0.   0.25 0.5  1.   0.  ]
[0.   0.   0.25 0.5  1.   0.  ]


In [149]:
print(v)

[0. 0. 0. 0. 1. 0.]


In [127]:
v = reward + gamma*np.roll(v,-1)

In [160]:
n=10

In [164]:
for i in range(0,n):
    vi = np.copy(v)
    v[:-1] = reward[:-1] + gamma* np.roll(v,-1)[:-1] 
    print(v-vi,v)

[0. 0. 0. 0. 1. 0.] [0. 0. 0. 0. 1. 0.]
[0.  0.  0.  0.5 0.  0. ] [0.  0.  0.  0.5 1.  0. ]
[0.   0.   0.25 0.   0.   0.  ] [0.   0.   0.25 0.5  1.   0.  ]
[0.    0.125 0.    0.    0.    0.   ] [0.    0.125 0.25  0.5   1.    0.   ]
[0.0625 0.     0.     0.     0.     0.    ] [0.0625 0.125  0.25   0.5    1.     0.    ]
[0. 0. 0. 0. 0. 0.] [0.0625 0.125  0.25   0.5    1.     0.    ]
[0. 0. 0. 0. 0. 0.] [0.0625 0.125  0.25   0.5    1.     0.    ]
[0. 0. 0. 0. 0. 0.] [0.0625 0.125  0.25   0.5    1.     0.    ]
[0. 0. 0. 0. 0. 0.] [0.0625 0.125  0.25   0.5    1.     0.    ]
[0. 0. 0. 0. 0. 0.] [0.0625 0.125  0.25   0.5    1.     0.    ]


In [159]:
print(v[:])

[0.   0.   0.25 0.5  1.   0.  ]


In [145]:
v = np.array([1.,2.,3.,4.,5.,6.])

In [146]:
for i in range(0,v.shape[0]-1):
    print(v)
    v[i] = gamma*v[i+1]
    print(v)
    #print(v-vi)

[1. 2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5. 6.]
[1.  1.5 3.  4.  5.  6. ]
[1.  1.5 3.  4.  5.  6. ]
[1.  1.5 2.  4.  5.  6. ]
[1.  1.5 2.  4.  5.  6. ]
[1.  1.5 2.  2.5 5.  6. ]
[1.  1.5 2.  2.5 5.  6. ]
[1.  1.5 2.  2.5 3.  6. ]


implement a deterministic markov decision process

In [197]:
nstates = 4
r = np.array([[0,1,0,0],[1,0,1,0],[0,1,0,10],[0,0,10,0]])
a = np.array([[0,1,0,0],[1,0,1,0],[0,1,0,1],[0,0,1,0]])
gamma = 0.75

In [198]:
v = np.zeros(nstates)
vf = np.zeros(nstates)
istate = 0
i = 0
imax = 100 #number of max iterations

In [199]:
for i in range(imax): #for all iterations
    #print("i=",i)
    for istate in range(nstates): #for all states
        #print("state=",istate)
        iactions = np.nonzero(a[istate])[0] #find what actions are allowed for that state
        #print("iactions=",iactions)
        voptions = np.zeros(iactions.shape[0]) #initialize v array for that state to enter the values for all actions
        n=0
        for action in iactions:
            voptions[n] = r[istate,action] + gamma * v[action]
            n = n + 1
        #print("voptions=",voptions)
        vf[istate] = np.amax(voptions)  #store the new v values in a temp array (current values are needed for updates)
        #print("vf[istate]=",vf[istate])
    v = np.copy(vf) #copy all new values to the v array
    print(i,v)

0 [ 1.  1. 10. 10.]
1 [ 1.75  8.5  17.5  17.5 ]
2 [ 7.375 14.125 23.125 23.125]
3 [11.59375 18.34375 27.34375 27.34375]
4 [14.7578125 21.5078125 30.5078125 30.5078125]
5 [17.13085938 23.88085938 32.88085938 32.88085938]
6 [18.91064453 25.66064453 34.66064453 34.66064453]
7 [20.2454834 26.9954834 35.9954834 35.9954834]
8 [21.24661255 27.99661255 36.99661255 36.99661255]
9 [21.99745941 28.74745941 37.74745941 37.74745941]
10 [22.56059456 29.31059456 38.31059456 38.31059456]
11 [22.98294592 29.73294592 38.73294592 38.73294592]
12 [23.29970944 30.04970944 39.04970944 39.04970944]
13 [23.53728208 30.28728208 39.28728208 39.28728208]
14 [23.71546156 30.46546156 39.46546156 39.46546156]
15 [23.84909617 30.59909617 39.59909617 39.59909617]
16 [23.94932213 30.69932213 39.69932213 39.69932213]
17 [24.0244916 30.7744916 39.7744916 39.7744916]
18 [24.0808687 30.8308687 39.8308687 39.8308687]
19 [24.12315152 30.87315152 39.87315152 39.87315152]
20 [24.15486364 30.90486364 39.90486364 39.90486364]
2

In [200]:
v

array([24.25, 31.  , 40.  , 40.  ])

find the best policy for each state (could have implemented it on the previous part of the code)

In [201]:
for istate in range(nstates): #for all states
    iactions = np.nonzero(a[istate])[0] #find what actions are allowed for that state
    voptions = np.zeros(iactions.shape[0]) #initialize v array for that state to enter the values for all actions
    n=0
    for action in iactions:
        voptions[n] = r[istate,action] + gamma * v[action]
        n = n + 1
    print(istate,iactions,voptions)

0 [1] [24.25]
1 [0 2] [19.1875 31.    ]
2 [1 3] [24.25 40.  ]
3 [2] [40.]


Q-value iteration algorithm

In [216]:
nstates = 6 #number of states
nactions = 2 #number of actions
a = np.array([0,1]) #0 = C, 1 = M actions array

In [232]:
#initialize transition probability array
t = np.zeros((nstates,nactions,nstates)) 
istate = 0
t[istate,:,istate]=1.
for istate in [4,5]:
    t[istate,1,istate-1]=1.
    t[istate,0,istate]=1.
for istate in [1,2,3]:
    t[istate,0,istate+2]=0.7
    t[istate,0,istate]=0.3
    t[istate,1,istate-1]=1.

In [233]:
t[3]

array([[0. , 0. , 0. , 0.3, 0. , 0.7],
       [0. , 0. , 1. , 0. , 0. , 0. ]])

In [254]:
#initialize rewards array
r = np.zeros((nstates,nactions,nstates)) 
for iaction in range(nactions):
    for istate in range(nstates):
        for iistate in range(nstates):
            if istate != iistate:
                r[istate,iaction,iistate] = np.abs(iistate-istate)**(1./3.)
            elif istate == iistate and istate !=0:
                r[istate,iaction,istate] = (istate+4.)**(-0.5)
            elif istate == iistate and istate ==0:
                r[istate,iaction,istate] = 0.

In [257]:
gamma = 0.6
q = np.zeros((nstates,nactions))
qf = np.copy(q)
imax = 1

In [258]:
for i in range(imax):
    for istate in range(nstates):
        for iaction in range(nactions):
            temp_sum = 0.
            for iistate in range(nstates):
                temp_sum = temp_sum + t[istate,iaction,iistate]*(r[istate,iaction,iistate] + gamma * np.amax(q[iistate,:]))
                #print("tempsum=",temp_sum)
            qf[istate,iaction] = temp_sum
            #print("state=",istate," action=",iaction," q=",qf[istate,iaction])
    q = np.copy(qf)
    print(i,"\n",q)
        

0 
 [[0.         0.        ]
 [1.01610881 1.        ]
 [1.00441922 1.        ]
 [0.99533408 1.        ]
 [0.35355339 1.        ]
 [0.33333333 1.        ]]


In [259]:
print(i,q)

0 [[0.         0.        ]
 [1.01610881 1.        ]
 [1.00441922 1.        ]
 [0.99533408 1.        ]
 [0.35355339 1.        ]
 [0.33333333 1.        ]]


In [227]:
np.amax(q[1,:])

1.348500273637058